### ISSUE TITLE
종료 코드 오류

### ISSUE THREAD

**Issue by gaarden** [gaarden/indianpokerface#17]
한쪽의 보유칩이 0 이하일 때 패배했다는 메시지를 출력하고 종료해야하는데, 종료한다고 말만 하고 또 게임을 그대로 진행한다.
![image](https://user-images.githubusercontent.com/72001106/145594352-07c8b4a8-196f-4771-a25e-2a97925c3aab.png)

-> 현재로는 게임 패배하면 아예 게임을 종료시켜버릴 생각인데, 그러면 소켓 통신을 아예 종료해야함. 소켓 종료 코드를 봐야할 듯

**Comment by thumbzzero** [comment]
고침!
