### ISSUE TITLE
종료 오류

### ISSUE THREAD

**Issue by gaarden** [gaarden/indianpokerface#21]
게임을 종료할 때, 한쪽에서는 종료 문구가 뜨지만 한쪽에서는 안뜬다.
두쪽 다 종료 문구가 뜨도록 하기

![image](https://user-images.githubusercontent.com/72001106/145659792-5cbdbdf1-82ba-4c5d-853c-efb2434f2af2.png)

**Comment by thumbzzero** [comment]
이긴 쪽에서 상대방 칩 개수 0 이하인지 체크하는 조건문 넣어서 해결(상대방 칩 개수 0이하이면 게임 종료 문구 출력)
