### ISSUE TITLE
초기 출력 오류

### ISSUE THREAD

**Issue by JeongDaH** [gaarden/indianpokerface#8]
#5 c1Num=newCard를 어디에 쓰느냐에 따라서 결과에 오류가 생깁니다.
두줄만 밑으로 순서를 바꿔도 server쪽에서는 화면에 출력되어야 할 코드가 출력되지 않습니다.
왜 그런지는 모르겠는데 일단은 랜덤함수가 문제인 것 같기도 합니다..

**Comment by ezzkimm** [comment]
흠 그렇습니까?
